version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    commit-message:
      prefix: '⬆️ '
    groups:
      actions-dependencies:
        patterns:
          - '*'
