blank_issues_enabled: false
contact_links:
  - name: Report an abandoned package dependency
    url: https://github.com/knuckleswtf/scribe/issues/589
    about: If you're getting the message "Package spatie/data-transfer-object is abandoned", go here.
